### ISSUE TITLE
"NotImplementedError" in SSVG 1.4.0

### ISSUE THREAD

**Issue by OrbitalMechanic** [whiskie14142/SolarSystemVoyager#3] opened 2019-09-21 19:24 UTC
I'm attempting to run the Python script SSVG.py on an iMacPro running Mac OS X 10.14.6 (Mojave) in the Anaconda distribution Python 3.7.x. When running the Python script the following traceback is generated:

(base) Samuels-Mac-Pro:source user$ python SSVG.py
Traceback (most recent call last):
  File "SSVG.py", line 1513, in <module>
    main()
  File "SSVG.py", line 1508, in main
    g.mainform = MainForm()
  File "SSVG.py", line 157, in __init__
    self.initSSV()
  File "SSVG.py", line 310, in initSSV
    self.init3Dfigure()
  File "SSVG.py", line 334, in init3Dfigure
    g.ax=g.fig.gca(projection='3d', aspect='equal')
  File "/Users/user/anaconda3/lib/python3.7/site-packages/matplotlib/figure.py", line 1932, in gca
    return self.add_subplot(1, 1, 1, **kwargs)
  File "/Users/user/anaconda3/lib/python3.7/site-packages/matplotlib/figure.py", line 1414, in add_subplot
    a = subplot_class_factory(projection_class)(self, *args, **kwargs)
  File "/Users/user/anaconda3/lib/python3.7/site-packages/matplotlib/axes/_subplots.py", line 69, in __init__
    self._axes_class.__init__(self, fig, self.figbox, **kwargs)
  File "/Users/user/anaconda3/lib/python3.7/site-packages/mpl_toolkits/mplot3d/axes3d.py", line 101, in __init__
    super().__init__(fig, rect, frameon=True, *args, **kwargs)
  File "/Users/user/anaconda3/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 509, in __init__
    self.update(kwargs)
  File "/Users/user/anaconda3/lib/python3.7/site-packages/matplotlib/artist.py", line 974, in update
    ret = [_update_property(self, k, v) for k, v in props.items()]
  File "/Users/user/anaconda3/lib/python3.7/site-packages/matplotlib/artist.py", line 974, in <listcomp>
    ret = [_update_property(self, k, v) for k, v in props.items()]
  File "/Users/user/anaconda3/lib/python3.7/site-packages/matplotlib/artist.py", line 971, in _update_property
    return func(v)
  File "/Users/user/anaconda3/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 1281, in set_aspect
    'It is not currently possible to manually set the aspect '
NotImplementedError: It is not currently possible to manually set the aspect on 3D axes
(base) Samuels-Mac-Pro:source user$

Is there anything that can be done to mitigate this?

Please advise.

Sam Dupree.

**Comment by whiskie14142** [comment] 2019-09-21 22:55
@OrbitalMechanic
Thanks to trying SSVG.
I encountered the same issue on the latest distribution of ANACONDA.  I think that It means the newer version of Matplotlib does not allow the "aspect" parameter for 3D gca.

Modify the line 334 of SSVG.py to eliminate the parameter of "aspect", it results into: 
g.ax=g.fig.gca(projection='3d')

Try it, I wish you enjoy SSVG!

**Comment by OrbitalMechanic** [comment] 2019-09-21 23:58
Thank you for responding to my post so quickly. I sincerely appreciate it.

I followed your advice and changed line 334 of SSVG.py to read: g.ax=g.fig.gca(projection='3d').

Running SSVG.py with this change gave rise to the following traceback:


================================================================================
September 21, 2019 at 19:05:31
~/SSVG_1_4_0/source/SSVG.py
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/user/SSVG_1_4_0/source/SSVG.py", line 1514, in <module>
    main()
  File "/Users/user/SSVG_1_4_0/source/SSVG.py", line 1509, in main
    g.mainform = MainForm()
  File "/Users/user/SSVG_1_4_0/source/SSVG.py", line 157, in __init__
    self.initSSV()
  File "/Users/user/SSVG_1_4_0/source/SSVG.py", line 310, in initSSV
    self.init3Dfigure()
  File "/Users/user/SSVG_1_4_0/source/SSVG.py", line 347, in init3Dfigure
    mngr.window.setGeometry(left+650, top, 700, 700)
AttributeError: 'FigureManagerMac' object has no attribute 'window'


In looking into the error message, "AttributeError: 'FigureManagerMac' object has no attribute 'window'", I came across a posting on stackoverflow,
https://stackoverflow.com/questions/20025077/how-do-i-display-a-matplotlib-figure-window-on-top-of-all-other-windows-in-spyde, that led me to
include the backend, matplotlib.use('QT5Agg'), following the import matplotlib statement (line 40 in SSVG.py).

Once I made the above change, I was able to SSVG to bring up the Flight Plan window. At this point, I opened the flight plan for the sample_swingby example. The attached .png file is the result.

SSVG seems to be running for me now.

Sam Dupree.

<img width="2048" alt="Screen Shot 2019-09-21 at 19 47 58" src="https://user-images.githubusercontent.com/4779511/65380451-0486b980-dcaa-11e9-96ad-58f50b860a6d.png">

**Comment by whiskie14142** [comment] 2019-09-22 05:24
@OrbitalMechanic
Thank you very much for the testing, the screenshot, and information.
I will add the statement "matplotlib.use('QT5Agg')" in the next version of SSVG.

The screenshot shows some issues around fonts of widgets.  I will check and try to fix them.

**Comment by whiskie14142** [comment] 2019-09-24 08:26
@OrbitalMechanic,
I checked the GUI design of SSVG and found many widgets without any font settings.  I fixed them and uploaded the updated code into the branch "Version1.4.1."  Could you try it?
The code includes "g.ax=g.fig.gca(projection='3d')" and "matplotlib.use('QT5Agg')" also.

**Comment by OrbitalMechanic** [comment] 2019-09-25 03:45
Shushi,

I ran branch version 1.4.1. I've attached a screen snap of  the windows 
displayed by SSVG. The only message output by SSVG to the terminal was:


(base) Samuels-Mac-Pro:source user$ python SSVG.py
objc[9131]: Class FIFinderSyncExtensionHost is implemented in both 
/System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit 
(0x7fff9854d3d8) and 
/System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride 
(0x1484b5f50). One of the two will be used. Which one is undefined.
(base) Samuels-Mac-Pro:source user$


Otherwise, the software runs just fine.

Hope this helps.

Sam Dupree.

**Comment by whiskie14142** [comment] 2019-09-25 04:59
@OrbitalMechanic 
Many thanks!  I cannot recognize the cause of the message but I am very happy to know SSVG runs well on your mac.
I wish to close this issue and continue some more works about SSVG v1.4.1.  If you wish to know the release of it, check #SSVG on twitter sometimes.

**Closed as completed by whiskie14142** 2019-09-25 04:59 UTC
